-- =============================================
-- SPEEDFAST
-- SCRIPT BASE DE DATOS ORACLE
-- =============================================


-- =============================================
-- TABLA REPARTIDORES
-- =============================================

CREATE TABLE repartidores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);


-- =============================================
-- TABLA PEDIDOS
-- =============================================

CREATE TABLE pedidos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direccion VARCHAR2(100) NOT NULL,
    tipo VARCHAR2(20),
    estado VARCHAR2(20),

    CONSTRAINT chk_pedidos_tipo
        CHECK (
            tipo IN (
                'COMIDA',
                'ENCOMIENDA',
                'EXPRESS'
            )
        ),

    CONSTRAINT chk_pedidos_estado
        CHECK (
            estado IN (
                'PENDIENTE',
                'EN_REPARTO',
                'ENTREGADO'
            )
        )
);


-- =============================================
-- TABLA ENTREGAS
-- =============================================

CREATE TABLE entregas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido NUMBER,
    id_repartidor NUMBER,
    fecha DATE,
    hora VARCHAR2(8),

    CONSTRAINT fk_entregas_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES pedidos(id),

    CONSTRAINT fk_entregas_repartidor
        FOREIGN KEY (id_repartidor)
        REFERENCES repartidores(id)
);